"""model: license_categories

Revision ID: 1abb479da794
Revises:
Create Date: 2025-12-22 17:06:36.420229

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1abb479da794"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "license_categories",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("license_categories")
    # ### end Alembic commands ###
